GET https://lv.blumbit.net/back/public/api/categoria
Accept: application/json
Authorization: Bearer 90|Katj3r8GyTKQofYANPCOdz8MDeambRLtt9QSmZy1ccdadbe6

##


POST https://lv.blumbit.net/back/public/api/categoria
Accept: application/json
Content-Type: application/json
Authorization: Bearer 76|QopHpBiO9dxP7YxBBaDETVECigqJ5fQZ5d6qEMlpb0bd842c

{
  "nombre": "DISOLVENTES",
  "detalle": "Prueba desde Angular"
}

##


PUT https://lv.blumbit.net/back/public/api/categoria/15
Accept: application/json
Content-Type: application/json
Authorization: Bearer 76|QopHpBiO9dxP7YxBBaDETVECigqJ5fQZ5d6qEMlpb0bd842c

{
  "nombre": "DISOLBENTES",
  "detalle": "Prueba desde Angular Modificado"
}
